
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    cap_add:
      - NET_ADMIN
    environment:
      - DB_HOST=db
      - DB_NAME=EasyConfig
      - DB_USER=postgres
      - GNS3_URL=${GNS3_URL}

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: EasyConfig
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d EasyConfig"]
      interval: 5s
      timeout: 5s
      retries: 5